export const Images = {
  BELL: require('../assets/bell.png'),
  CHART: require('../assets/chart.png'),
  HELP: require('../assets/help.png'),
  HISTORY: require('../assets/history.png'),
  HOME: require('../assets/home.png'),
  LOGOUT: require('../assets/logout.png'),
  PIGEON: require('../assets/pigeon.png'),
  QR_CODE: require('../assets/qr-code.png'),
  WALLET: require('../assets/wallet.png'),
  CLOSE_EYE: require('../assets/closeEye.png'),
  OPEN_EYE: require('../assets/openEye.png'),
  RIGHT: require('../assets/right.png'),
  WRONG: require('../assets/wrong.png'),

  // new images
  POSTER: require('../assets/poster2x.png'),
  POSTER_1X: require('../assets/poster1x.png'),
  POSTER_2X: require('../assets/poster.png'),
  NEW_POSTER: require('../assets/newMcsPoster.png'),
  LOGO: require('../assets/newLogo.png'),
  LOGO_2X: require('../assets/newLogo2x.png'),
  HEART: require('../assets/heart.png'),
  COUPLE: require('../assets/couple.png'),
  RUN: require('../assets/run.png'),
  LUCY: require('../assets/lucy.png'),
  BEN: require('../assets/ben.png'),
  CALCULATOR_2X: require('../assets/calculator2x.png'),
  CALENDER: require('../assets/calendar.png'),
  AFTER_WORKOUT: require('../assets/afterWorkout.png'),
  DOWN_ARROW: require('../assets/downArrow.png'),
  MARK: require('../assets/mark.png'),
  FACEBOOK_IMAGES: require('../assets/faceBookImage.png'),
  MEMBERSHIP_NEW2X: require('../assets/membershipNew2x.png'),
  NEW_POSTER_1: require('../assets/newMcsPoster1.png'),
  NEW_POSTER_2: require('../assets/newMcsPoster2.png'),
  NEW_POSTER_3: require('../assets/newMcsPoster3.png'),
  NEW_POSTER_4: require('../assets/newMcsPoster4.png'),
  NEW_POSTER_5: require('../assets/newMcsPoster5.png'),
  NEW_POSTER_6: require('../assets/newMcsPoster6.png'),
  NEW_POSTER_7: require('../assets/newMcsPoster7.png'),

  // bottom tab icons
  HOME_INACTIVE: require('../assets/subtractNew.png'),
  HOME_ACTIVE: require('../assets/subtractActive.png'),
  WORKOUT: require('../assets/workouts.png'),
  WORKOUT_ACTIVE: require('../assets/workoutsActive.png'),
  TRACK: require('../assets/track.png'),
  TRACK_ACTIVE: require('../assets/trackActive.png'),
  NUTRITION: require('../assets/nutrition.png'),
  NUTRITION_ACTIVE: require('../assets/nutritionActive.png'),
  LEARN: require('../assets/learn.png'),
  LEARN_ACTIVE: require('../assets/learnActive.png'),

  // icons
  BACK: require('../assets/back.png'),
  BACK_ARROW: require('../assets/backArrow.png'),
  CAMERA_BUTTON: require('../assets/cameraButton.png'),
  CAMERA_ICON: require('../assets/cameraIcon.png'),
  PHOTO_GALLERY: require('../assets/photoGallery.png'),
  CHANGE_VIEW: require('../assets/changeView.png'),
  CLOSE: require('../assets/close.png'),
  CAMERA: require('../assets/camera.png'),
  ROUNDED_CLOSE: require('../assets/roundedClose.png'),
  RIGHT_ARROW: require('../assets/rightArrow.png'),
  NO_WIFI_2X: require('../assets/noWifi2x.png'),
  CHALLENGE: require('../assets/challenge.png'),
  YES: require('../assets/yes.png'),
  LOCK: require('../assets/lock.png'),
  PROFILE_SETTINGS: require('../assets/profileSettings.png'),
  PLUS: require('../assets/plus.png'),
  ARROW_RIGHT: require('../assets/arrowRight.png'),
  TICK: require('../assets/tick.png'),
  ROUND_TICK: require('../assets/roundTick.png'),
  DRAGGABLE_ICON: require('../assets/draggableIcon.png'),
  SMILEY_3X: require('../assets/smiley3x.png'),
  COMPLETED_TICK: require('../assets/tickActive.png'),
  INCOMPLETE_TICK: require('../assets/tickInactive.png'),
  WORKOUT_REST_TIMER: require('../assets/timerImage.png'),
  STOPWATCH: require('../assets/stopwatch.png'),
  PLAYBUTTON_ARROW: require('../assets/playButtonArrow.png'),
  PLAY_BUTTON: require('../assets/play.png'),
  PAUSE_BUTTON: require('../assets/pause.png'),

  // Permissions Screens icons
  ANALYTICS: require('../assets/analyticsPermission.png'),
  HEALTH_PERMISSIONS: require('../assets/healthNew.png'),
  PREFERENCES: require('../assets/settings.png'),

  PROFILE_STAR: require('../assets/starTag.png'),
  PROFILE_MEMBERSHIPTYPE: require('../assets/membershiptypeLogo.png'),
  INPUT_FIELD_RIGHT_ICON: require('../assets/inputFieldRight.png'),
  EMPTY_HEART: require('../assets/emptyHeart.png'),
  FACEBOOK_ICON: require('../assets/facebookIcon.png'),

  // nutrition screen
  PASTA_2X: require('../assets/pasta2x.png'),

  // track screen icon
  REQUEST_PLAN_3X: require('../assets/requestPlan3x.png'),
  TRACK_DUMBLE_3X: require('../assets/trackDumbbell3x.png'),
  GOAL_3X: require('../assets/trackGoal3x.png'),
  METRIC_3X: require('../assets/trackMetric3x.png'),
  PROGRESS_3X: require('../assets/trackProgress3x.png'),
  STEP_3X: require('../assets/trackStep3x.png'),

  // For Testing
  LUCY_WORKOUT: require('../assets/lucyWorkout.png'),
  TESTING: require('../assets/testing.png'),

  MOVE_ARROW_LEFT: require('../assets/moveArrowLeft.png'),
  MOVE_ARROW_RIGHT: require('../assets/moveArrowRight.png'),
  SOMETHING_WENT_WRONG: require('../assets/somethingWentWrong.png'),

  WALK: require('../assets/walk.png'),
  CALORIE: require('../assets/calories.png'),

  FINGERPRINT: require('../assets/fingerprint.png'),
  FACELOCK: require('../assets/faceLock.png'),
  DOTS: require('../assets/dots.png'),

  //Static Images(Will Change Later)
  STATIC_HOME_SCREEN_ENROLLED_PROGRAMME_IMAGE: require('../assets/EnrolledWorkoutHomeScreen.png'),
  STATIC_HOME_SCREEN_CHALLENGE_IMAGE: require('../assets/CommunityAndChallenge.png'),
  STATIC_HOME_SCREEN_COMMUNITY_IMAGE: require('../assets/CommunityAndChallenge.png'),
  STATIC_RECIPES_MAIN_CATEGORY_IMAGE: require('../assets/RecipeScreenMainCategory.png'),
  STATIC_LESSON_MAIN_CATEGORY_IMAGE: require('../assets/LearnScreenMainCategory.png'),
  STATIC_PROGRAMME_IMAGE: require('../assets/LearnScreenMainCategory.png'),
  STATIC_WORKOUT_IMAGE: require('../assets/LearnScreenMainCategory.png'),
  STATIC_RECIPE_IMAGE: require('../assets/LearnScreenWithLevel.png'),
  STATIC_LESSON_IMAGE_WITHOUT_LEVEL: require('../assets/LearnScreenWithoutLevel.png'),
  STATIC_LESSON_IMAGE_WITH_LEVEL: require('../assets/LearnScreenWithLevel.png'),
  STATIC_FAVOURITE_RECIPE_IMAGE: require('../assets/HomeScreenFavWorkoutsFavRecipes.png'),
  STATIC_FAVOURITE_WORKOUT_IMAGE: require('../assets/HomeScreenFavWorkoutsFavRecipes.png'),
  STATIC_WORKOUT_EXERCISES_IMAGE: require('../assets/staticImage.jpeg'),
  STATIC_PROFILE_SCREEN_PROFILE_IMAGE: require('../assets/ProfileScreenProfileImage.png'),
  STATIC_HOME_SCREEN_PROFILE_IMAGE: require('../assets/HomeScreenProfileImage.png'),
};
